(ns bloqz.levels)

(def lvl-list [[{:id 0 :type :horizontal :size 2 :x 0 :y 2}
                {:id 1 :type :horizontal :size 3 :x 0 :y 0}
                {:id 2 :type :horizontal :size 2 :x 4 :y 3}
                {:id 3 :type :horizontal :size 3 :x 0 :y 5}
                {:id 4 :type :vertical   :size 3 :x 2 :y 1}
                {:id 5 :type :vertical   :size 2 :x 0 :y 3}
                {:id 6 :type :vertical   :size 3 :x 5 :y 0}
                {:id 7 :type :vertical   :size 2 :x 4 :y 4}]
               [{:id 0 :type :horizontal :size 2 :x 0 :y 2}
                {:id 1 :type :horizontal :size 2 :x 0 :y 3}
                {:id 2 :type :horizontal :size 2 :x 2 :y 5}
                {:id 3 :type :vertical   :size 2 :x 1 :y 4}
                {:id 4 :type :vertical   :size 2 :x 2 :y 1}
                {:id 5 :type :vertical   :size 2 :x 2 :y 3}
                {:id 6 :type :vertical   :size 3 :x 3 :y 1}
                {:id 7 :type :vertical   :size 3 :x 4 :y 1}]
               [{:id 0 :type :horizontal :size 2 :x 0 :y 2}
                {:id 1 :type :horizontal :size 2 :x 1 :y 0}
                {:id 2 :type :horizontal :size 2 :x 3 :y 0}
                {:id 3 :type :horizontal :size 3 :x 0 :y 4}
                {:id 4 :type :vertical   :size 2 :x 0 :y 0}
                {:id 5 :type :vertical   :size 2 :x 2 :y 1}
                {:id 6 :type :vertical   :size 3 :x 3 :y 2}
                {:id 7 :type :vertical   :size 3 :x 4 :y 2}]
               [{:id 0 :type :horizontal :size 2 :x 0 :y 2}
                {:id 1 :type :horizontal :size 2 :x 0 :y 3}
                {:id 2 :type :horizontal :size 2 :x 2 :y 4}
                {:id 3 :type :horizontal :size 2 :x 2 :y 5}
                {:id 4 :type :vertical   :size 3 :x 3 :y 1}
                {:id 5 :type :vertical   :size 3 :x 4 :y 1}
                {:id 6 :type :vertical   :size 2 :x 5 :y 1}
                {:id 7 :type :vertical   :size 2 :x 1 :y 4}]
               [{:id 0  :type :horizontal :size 2 :x 2 :y 2}
                {:id 1  :type :horizontal :size 2 :x 3 :y 0}
                {:id 2  :type :horizontal :size 2 :x 0 :y 1}
                {:id 3  :type :horizontal :size 2 :x 2 :y 3}
                {:id 4  :type :horizontal :size 2 :x 2 :y 4}
                {:id 5  :type :horizontal :size 2 :x 4 :y 4}
                {:id 6  :type :horizontal :size 2 :x 0 :y 5}
                {:id 7  :type :vertical   :size 2 :x 2 :y 0}
                {:id 8  :type :vertical   :size 2 :x 5 :y 0}
                {:id 9  :type :vertical   :size 2 :x 5 :y 2}
                {:id 10 :type :vertical   :size 2 :x 4 :y 1}
                {:id 11 :type :vertical   :size 2 :x 0 :y 2}
                {:id 12 :type :vertical   :size 3 :x 1 :y 2}]])
